---
- hosts: tower
  gather_facts: yes
  become: true
  tasks:
    - name: "Check if vsftpd is installed"
      package_facts:
         manager: "auto"
    - name: "vsftpd result"
      debug:
         msg: "vsftpd found"
      when: "'vsftpd' in ansible_facts.packages"
    - name: "vsftpd result"
      debug:
         msg: "vsftpd NOT found"
      when: "'vsftpd' not in ansible_facts.packages"

    - name: "Check if httpd is installed"
      package_facts:
        manager: "auto"
    - name: "httpd result"
      debug:
         msg: "httpd found"
      when: "'httpd' in ansible_facts.packages"
    - name: "httpd result"
      debug:
         msg: "httpd NOT found"
      when: "'httpd' not in ansible_facts.packages"
